UNB/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from sitemaps import MilSitemap
from django.views.generic import TemplateView

sitemaps = {"mil": MilSitemap}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="home"),
    path("", include("board.urls")),
    path("", include("allauth.urls")),
    path(
        "sitemap.xml/",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path("mil/create/", views.MilitaryCreateView.as_view(), name="mil_create"),
    path("mil/<int:pk>", views.MilitaryDetailView.as_view(), name="mil_detail"),
    path("mil/<int:pk>/update/", views.MilitaryUpdateView.as_view(), name="mil_update"),
    path("mil/<int:pk>/delete/", views.military_delete, name="mil_delete"),
    path("comment/create/", views.comment_create, name="cmt_create"),
    path("comment/delete/", views.comment_delete, name="cmt_delete"),
    path("comment/update/", views.comment_update, name="cmt_update"),
    path("like/", views.like, name="like"),
    path("image/", views.image, name="image"),
]

board/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta


class Military(models.Model):
    CHOICES = [
        ("F", "자유"),
        ("N", "소식"),
        ("C", "정보"),
        ("A", "공지"),
    ]
    category = models.CharField(max_length=2, choices=CHOICES)
    title = models.CharField(max_length=32, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="작성자")
    date = models.DateTimeField(auto_now_add=True, verbose_name="작성일")
    view = models.PositiveIntegerField(default=0, verbose_name="조회수")
    like = models.PositiveIntegerField(default=0, verbose_name="추천수")
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='LU')
    score = models.PositiveIntegerField(default=0, verbose_name="점수")

    @property
    def date_str(self):
        if self.date.strftime("%Y%m%d") == datetime.now().strftime("%Y%m%d"):
            return self.date.strftime("%H:%M")
        else:
            return self.date.strftime("%m-%d")

    @property
    def new(self):
        if datetime.now() - timedelta(hours=3) < self.date:
            return True
        else:
            return False

    @property
    def view_count(self):
        self.view += 1
        self.score += 1
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        db_table = "Military"
        verbose_name = "밀리터리"
        verbose_name_plural = "밀리터리"
        ordering = ["-date"]


class Comment(models.Model):
    board = models.ForeignKey(
        Military, null=True, blank=True, on_delete=models.CASCADE, verbose_name="게시글"
    )
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="작성자")
    content = models.CharField(max_length=1024, verbose_name="내용")
    date = models.DateTimeField(auto_now_add=True, verbose_name="작성일")
    parents = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        related_name="recomment",
        null=True,
        verbose_name="작성자",
    )

    @property
    def date_str(self):
        if self.date.strftime("%Y%m%d") == datetime.now().strftime("%Y%m%d"):
            return self.date.strftime("%H:%M")
        else:
            return self.date.strftime("%m-%d")

    class Meta:
        db_table = "Comment"
        verbose_name = "댓글"
        verbose_name_plural = "댓글"


class Image(models.Model):
    image = models.ImageField(null=True, blank=True, upload_to="%Y-%m-%d/")

templates/form.html
{% extends "index.html" %}
{% block head %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
<link rel="stylesheet" type="text/css" href="/static/form.css">
{% endblock head %}
{% block board %}
<form id="form" method="post" onsubmit="return check(this)">
    {% csrf_token %}
    <div id="main">
        <select name="category" id="category">
            <option value="F">자유</option>
            <option value="N">소식</option>
            <option value="C">정보</option>
        </select>
        <script>
            var sel = "{{form.category.value}}";
            if (sel != "None") {
                document.getElementById('category').value = sel;
            }
        </script>
        {{form.title}}
        {{form.content|safe}}
    </div>
    <div class="buttons">
        <input id="done" type="submit" value="등록">
        <button id="cancel" onclick="window.history.back();" type="button">취소</button>
    </div>
</form>
<script>
    function check(form) {
        var test = $('#id_content').summernote().val().replace(/\s/g, '').replace(/<(\/p|p|br|br)([^>]*)>/gi, "").replace(/&nbsp;/ig, "");
        if ($("#id_title").val().trim() == "") {
            alert("제목을 입력해주세요.");
            return false;
        }
        else if (test == "") {
            alert("내용을 입력해주세요.")
            return false;
        }
    }
    function uuidv4() {
        return 'xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }
    $(document).ready(function () {
        $('#id_content').summernote({
            minHeight: 500,
            maxHeight: 1325,
            lang: 'ko-KR',
            toolbar: [
                ['font', ['bold', 'underline', 'strikethrough', 'clear']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture']],
                ['view', ['fullscreen']],
            ],
            callbacks: {
                onImageUpload: function (files) {
                    if (!files.length) return;
                    var file = files[0];
                    console.log(file.type)
                    if (file.type == 'image/jpg' || file.type == 'image/jpeg' || file.type == 'image/gif' || file.type == 'image/png') {
                        var fileName = uuidv4(file.name.split('.')[0]);
                        var img = new Image();
                        img.src = URL.createObjectURL(file);
                        img.onload = function () {
                            var canvas = document.createElement('canvas');
                            var maxsize = 600;
                            var width = img.width;
                            var height = img.height;
                            if (width > height) {
                                if (width > maxsize) {
                                    height *= maxsize / width;
                                    width = maxsize;
                                }
                            } else {
                                if (height > maxsize) {
                                    width *= maxsize / height;
                                    height = maxsize;
                                }
                            }
                            canvas.width = width;
                            canvas.height = height;
                            var ctx = canvas.getContext('2d');
                            ctx.drawImage(img, 0, 0, width, height);
                            canvas.toBlob(function (blob) {
                                var f2 = new File([blob], fileName + ".jpeg");
                                var data = new FormData()
                                data.append("file", f2)
                                data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
                                $.ajax({
                                    data: data,
                                    type: "POST",
                                    url: "{% url 'board:image' %}",
                                    contentType: false,
                                    processData: false,
                                    success: function (response) {
                                        var image = $("<img>").attr({ src: response.url });
                                        $('#id_content').summernote("insertNode", image[0]);
                                    }
                                });
                            }, 'image/jpeg', 0.7);
                        }
                    } else {
                        alert("jpg, png, jpeg, gif 형식의 이미지만 업로드 가능합니다.");
                    }
                }
            }
        }).on("summernote.enter", function (we, e) {
            $(this).summernote("pasteHTML", "<br><br>");
            e.preventDefault();
        });;
    });
    $(window).on('beforeunload', function () {
        return "";
    });
    $(document).on("submit", "form", function () {
        $(window).off('beforeunload');
    });
</script>
{% endblock board %}

templates/index.html
<!DOCTYPE html>
<html lang="ko">
{% load socialaccount %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google-site-verification" content="Uo6wtUJ5JJuq7oeydXzIFuUIS9DJFzY4M9ZicU04Bgk" />
    <meta name="naver-site-verification" content="d664d44daa134288801fdd59dfea8046759604c6" />
    <meta property="og:type" content="website">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/index.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="shortcut icon" href="/static/favicon.ico">
    <meta name="author" content="포밀덕">
    <meta name="keywords" content="포밀덕, 밀리터리, 밀덕, 군사, 군대, 군갤, 군사뉴스, 국방뉴스, 국방신문, 군사커뮤니티, 밀덕커뮤니티, 밀덕사이트, 군사사이트">
    <meta property="og:locale" content="ko_KR">
    <meta property="og:site_name" content="포밀덕">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8572587507451544"
        crossorigin="anonymous"></script>

    {% block head %}
    <title>포밀덕</title>
    <meta name="description" content="밀덕을 위한 군사 커뮤니티 포밀덕">
    <meta name="title" content="포밀덕">
    <meta property="og:title" content="포밀덕">
    <meta property="og:description" content="밀덕을 위한 군사 커뮤니티 포밀덕">
    <meta property="og:url" content="https://4millduk.com/">
    {% endblock head %}

</head>

<body>
    <header>
        <a href="/">
            <img src="/static/logo.png" style="image-rendering:-webkit-optimize-contrast;width:100%;">
        </a>
        <div style="width:100%;background:#f1f1f1;"></div>
    </header>
    <main>
        <article>
            {% block board %}
            <section id="search">
                <select id="S">
                    <option value="W">전체</option>
                    <option value="N">소식</option>
                    <option value="C">정보</option>
                    <option value="F">자유</option>
                    <option value="A">공지</option>
                </select>
                <input onchange="get_z()" value="{{z}}" id="Z" placeholder="검색어를 입력해주세요.">
                <button id="go_search">
                    검색
                </button>
                <script>
                    if ("{{z}}" != "") {
                        document.getElementById('S').value = "{{s}}";
                    }
                    function get_z() {
                        $("#go_search").click(function () {
                            var s = document.getElementById("S").value;
                            var z = document.getElementById("Z").value;
                            if (z.length <= 1) {
                                alert("두글자 이상의 단어를 검색해주세요.")
                            } else {
                                location.href = "?z=" + z + "&s=" + s;
                            }
                        });
                    }
                </script>
            </section>
            <section id="list">
                <ul id="category">
                    <li id="W">
                        {% if z == "" %}
                        <a href="/" id="W">
                            {% else %}
                            <a href="?z={{z}}&s=W" id="W">
                                {% endif %}
                                <i class="fa-solid fa-earth-americas"></i> 전체
                            </a>
                    </li>
                    <li>
                        {% if z == "" %}
                        <a href="?s=N" id="N">
                            {% else %}
                            <a href="?z={{z}}&s=N" id="N">
                                {% endif %}
                                <i class="fa-solid fa-bullhorn"></i> 소식
                            </a>
                    </li>
                    <li>
                        {% if z == "" %}
                        <a href="?s=C" id="C">
                            {% else %}
                            <a href="?z={{z}}&s=C" id="C">
                                {% endif %}
                                <i class="fa-solid fa-square-poll-horizontal"></i> 정보
                            </a>
                    </li>
                    <li>
                        {% if z == "" %}
                        <a href="?s=F" id="F">
                            {% else %}
                            <a href="?z={{z}}&s=F" id="F">
                                {% endif %}
                                <i class="fa-solid fa-comments"></i> 자유
                            </a>
                    </li>
                    <li>
                        {% if z == "" %}
                        <a href="?s=A" id="A">
                            {% else %}
                            <a href="?z={{z}}&s=A" id="A">
                                {% endif %}
                                <i class="fa-solid fa-circle-info"></i> 공지
                            </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <button>
                        <a href="{% url 'board:mil_create' %}">
                            <i class="fa-solid fa-feather"></i> 글쓰기
                        </a>
                    </button>
                    {% else %}
                    <button onclick="alert('로그인이 필요한 기능입니다.')">
                        <i class="fa-solid fa-feather"></i> 글쓰기
                    </button>
                    {% endif %}
                </ul>
                <script>
                    $(document).ready(function () {
                        var s = "{{s}}"
                        if (s == "" || s == "W") {
                            $("#W a").css("color", "#606060");
                            $("#W i").css("fill", "#606060");
                        }
                        else {
                            $("#" + s).css("color", "#606060");
                            $("#" + s + "  i").css("fill", "#606060");
                        }
                    });
                </script>
                {% if page_obj %}
                <table>
                    <thead>
                        <tr style="background:#fbfbfb;border-radius:8px;">
                            <th style="border-top-left-radius:8px;">번호</th>
                            <th>분류</th>
                            <th>제목</th>
                            <th>조회</th>
                            <th>추천</th>
                            <th style="border-top-right-radius:8px;">작성일</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in page_obj %}
                        <tr>
                            <td id="nu">{{ i.id }}</td>
                            <td id="ca" style="font-weight:bold;font-size:1.3rem;">
                                {% if i.category == "N" %}
                                <i class="fa-solid fa-bullhorn"></i> 소식
                                {% elif i.category == "C" %}
                                <i class="fa-solid fa-square-poll-horizontal"></i> 정보
                                {% elif i.category == "F" %}
                                <i class="fa-solid fa-comments"></i> 자유
                                {% else %}
                                <i class="fa-solid fa-circle-info"></i> 공지
                                {% endif %}
                            </td>
                            <td id="ti" style="text-align:left;">
                                <a href="{% url 'board:mil_detail' i.pk %}" target="_self">
                                    {% if "img" in i.content %}
                                    <i class="fa-solid fa-image"></i>
                                    {% else %}
                                    <i class="fa-solid fa-file-lines"></i>
                                    {% endif %}
                                    {{ i.title|truncatechars:45 }} <span id="cmt_count">({{i.comment_set.count}})</span>
                                    {% if i.new %}
                                    <span id="new">N</span>
                                    {% endif %}
                                </a>
                            </td>
                            <td id="vi">{{ i.view }}</td>
                            <td id="li">{{ i.like }}</td>
                            <td id="da">{{ i.date_str }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div>
                    글이 존재하지 않습니다.
                </div>
                {% endif %}
                {% if page_obj %}
                <ul id="page-list">
                    {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li>{{ i }}</li>
                    {% elif i > page_obj.number|add:'-7' and i < page_obj.number|add:'7' %} <li>
                        {% if z == "" %}
                        {% if s == "" %}
                        <a href="?page={{ i }}">{{ i }}</a>
                        {% else %}
                        <a href="?s={{s}}&page={{ i }}">{{ i }}</a>
                        {% endif %}
                        {% else %}
                        <a href="?z={{z}}&s={{s}}&page={{ i }}">{{ i }}</a>
                        {% endif %}
                        </li>
                        {% endif %}
                        {% endfor %}
                </ul>
                {% endif %}
            </section>
            {% endblock board %}
        </article>
        <aside>
            <section id="login">
                {% if request.user.is_authenticated %}
                <form action="{% url 'account_logout' %}" method="post">
                    {% csrf_token %}
                    <button id="logout" type="submit">로그아웃</button>
                </form>
                {% else %}
                <form action="{% provider_login_url 'naver' %}" method="post">
                    {% csrf_token %}
                    <button id="naver" type="submit">
                        <img style="image-rendering: -webkit-optimize-contrast;" src="/static/naver.png">
                        <span style="color:#fff">네이버 로그인</span>
                    </button>
                </form>
                <form action="{% provider_login_url 'kakao' %}" method="post">
                    {% csrf_token %}
                    <button id="kakao" type="submit">
                        <img style="image-rendering: -webkit-optimize-contrast;" src="/static/kakao.png">
                        <span>카카오 로그인</span>
                    </button>
                </form>
                <form action="{% provider_login_url 'google' %}" method="post">
                    {% csrf_token %}
                    <button id="google" type="submit">
                        <img style="image-rendering: -webkit-optimize-contrast;" src="/static/google.png">
                        <span>구글 로그인</span>
                    </button>
                </form>
                {% endif %}
            </section>
            <section id="best">
                <div>
                    <i class="fa-solid fa-fire"></i> 인기 글
                </div>
                <ul>
                    {% for i in hot %}
                    <li>
                        <a href="{% url 'board:mil_detail' i.id %}">
                            <i class="fa-solid fa-fire"></i>
                            <span>
                                {% if i.category == "N" %}
                                <i class="fa-solid fa-bullhorn"></i> 소식
                                {% elif i.category == "C" %}
                                <i class="fa-solid fa-square-poll-horizontal"></i> 정보
                                {% elif i.category == "F" %}
                                <i class="fa-solid fa-comments"></i> 자유
                                {% else %}
                                <i class="fa-solid fa-circle-info"></i> 공지
                                {% endif %}
                            </span>
                            {{ i.title|truncatechars:16 }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </section>
            <div style="width:100%;height:300px;background:#f1f1f1;">
            </div>
        </aside>
    </main>
    <footer>
        Copyright 2022. 4MILLDUK all rights reserved.
    </footer>
</body>

</html>